apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: django-k8s
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: web
  selector:
    app: nginx-webserver