FROM python:3.9.10-slim

COPY . /app
WORKDIR /app


RUN python3 -m venv /opt/venv

RUN apt-get update && \
    apt-get -y install libpq-dev gcc && \
    /opt/venv/bin/pip install pip --upgrade && \
    /opt/venv/bin/pip install -r requirements.txt && \
    chmod +x entrypoint.sh

CMD ["/app/entrypoint.sh"]
